CREATE TABLE IF NOT EXISTS `CS_Admin_Bans` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `player_name` VARCHAR(100) NOT NULL,
  `identifiers` TEXT NOT NULL,
  `reason` VARCHAR(255) NOT NULL,
  `duration` VARCHAR(20) NOT NULL,
  `expires_at` DATETIME NOT NULL,
  `admin_name` VARCHAR(100) NOT NULL,
  `timestamp` TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
